# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    # configure resolvers
    resolvers:

        # setup the default resolver
        default:

            # use the default web path
            web_path: ~

    filter_sets:
        cache: ~
        my_thumb:
            quality: 45
            filters:
                thumbnail:
                    size: [800, 400]
                    mode: outbound

