vich_uploader:
    db_driver: orm

    mappings:
        item_image:
            uri_prefix: /items/images
            upload_destination: '%kernel.project_dir%/public/items/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
